// <auto-generated />
using System;
using Darvyn_Lavandier_P2_AP1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Darvyn_Lavandier_P2_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250323144658_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ciudad", b =>
                {
                    b.Property<int>("CiudadesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadesId"));

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CiudadesId");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            CiudadesId = 1,
                            Monto = 0,
                            Nombre = "San Francisco de Macoris"
                        },
                        new
                        {
                            CiudadesId = 2,
                            Monto = 0,
                            Nombre = "La Romana"
                        },
                        new
                        {
                            CiudadesId = 3,
                            Monto = 0,
                            Nombre = "Salcedo"
                        });
                });

            modelBuilder.Entity("Darvyn_Lavandier_P2_AP1.Models.Encuesta", b =>
                {
                    b.Property<int>("EncuestasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncuestasId"));

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("EncuestasId");

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("EncuestaDetalle", b =>
                {
                    b.Property<int>("DestallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestallesId"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<int>("MontoEncuesta")
                        .HasColumnType("int");

                    b.HasKey("DestallesId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EncuestaId");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("EncuestaDetalle", b =>
                {
                    b.HasOne("Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Darvyn_Lavandier_P2_AP1.Models.Encuesta", null)
                        .WithMany("EncuestaDetalles")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("Darvyn_Lavandier_P2_AP1.Models.Encuesta", b =>
                {
                    b.Navigation("EncuestaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
